### PR TITLE
Bundle2 #Exercice1: Create of PR

### PR DESCRIPTION
**Pull request by kunda4**
This PR is for creating new file service.html add changes and create PR

### CODE REVIEW

**Review by devfabien — CHANGES_REQUESTED** [review]

**Review by devfabien — CHANGES_REQUESTED** [review]
that is to check if

**Review by devfabien — APPROVED** [review]
everything set

**Review by devfabien — APPROVED** [review]

**Review by kareraolivier — APPROVED** [review]
Good work little sis.

**Review by IbrahimBagalwa — CHANGES_REQUESTED** [review]
@kunda4  could you please share the code snippet for the command you were typing earlier? It would be really helpful for me to understand what you were doing.

**Review by IbrahimBagalwa — APPROVED** [review]
LGTM 👍

**Pull request merged**
